# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Source Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = true
show_testing_output = false

# Shadow
enable_shadow = false

# Set this to true if you want to use old LWJGL2 methods.
enable_lwjglx = true

# Target Versions
minecraft_version = 1.12.2
ae2_mod_version = v1.0.10

# Mod Information
mod_version = 1.0.0
root_package = me.ramidzkh
mod_id = mekeng
mod_name = Applied Mekanistics

# Mod Metadata
mod_description = Use Mekanism resources through your ME network
mod_url = https://github.com/FormlessDragon/Applied-Mekanistics
mod_issue_tracker_url = https://github.com/FormlessDragon/Applied-Mekanistics/issues
mod_update_json =
mod_authors = FormlessDragon
mod_credits =
mod_logo_path = logo.png

# Catalogue Extra Metadata
mod_license = See GitHub repository for details
mod_icon_path =
mod_icon_item =
mod_background_path =

# Run Configurations
minecraft_username = Developer
extra_jvm_args =
enable_foundation_debug = false

# Maven Publishing
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =
maven_group=${root_package}
maven_artifact_id=${mod_id}
maven_developer_id=FormlessDragon
maven_developer_name=FormlessDragon
maven_license_name=${mod_license}
maven_license_url=https://www.gnu.org/licenses/lgpl-3.0.txt
maven_scm_url=${mod_url}

# Access Transformers
use_access_transformer = false
access_transformer_locations = ${mod_id}_at.cfg

# Coremods
is_coremod = false
coremod_includes_mod = true
coremod_plugin_class_name =

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
