name: Build mod jar

on:
  workflow_dispatch:
  push:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: FormlessDragon/.github/.github/workflows/build.yml@main
    secrets: inherit
    permissions:
      contents: write
