name: Runtime Test

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    branches: [main]
  merge_group:

permissions:
  contents: read
  actions: write

jobs:
  runtime-test:
    uses: FormlessDragon/.github/.github/workflows/runtime-test.yml@main
    secrets: inherit
